### ISSUE TITLE
Ethereum Client Parity (POA) and Encrypted Smart Contract

### ISSUE THREAD

**Issue by Amaleid** [pubkey/eth-crypto#10]
Hi 
Im new in this filed im using Ethereum Client Parity (POA) and im trying to create a Encrypted Smart Contract?
before i start is this tutorial will help and is its work with Parity ?

**Comment by pubkey** [comment]
Hi @Amaleid 
I'm sorry but the issues for this repo are to report bugs and make feature requests. Please ask your questions somewhere else like
https://gitter.im/ethereum/web3.js or https://www.reddit.com/r/ethdev/
