### ISSUE TITLE
how to work in browser

### ISSUE THREAD

**Issue by f5cs** [pubkey/eth-crypto#11]
hi pubkey:
  i compile the code into running on browser:
  var r = eciesCrypto.encryptWithPublicKey("pubKey","msg");
then r is:
    [[PromiseStatus]]:"pending"
    [[PromiseValue]]:undefined
the problem occurs by await,how to resolve it?
thks very much

**Comment by pubkey** [comment]
Hi @f5cs 
I'm sorry but this code does not help to understand your problem. Please reopen with a better description.
