### ISSUE TITLE
First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.

### ISSUE THREAD

**Issue by DDimovska** [pubkey/eth-crypto#13]
I have exact the same code, but when the decryptWithPrivateKey is called it returns: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.

```js
const encryptedMessage = await EthCrypto.encryptWithPublicKey(
        '0a1d34c4b12abb875ca0c73c5b97c6e680b7be45a5902202cb6a169a679e71f87d451561bdb946531565727dfacb741a612658e908f237916f65f51632b9fff6', 
        'foobar'
    );

const message = await EthCrypto.decryptWithPrivateKey(
        '0x814f37115168da9e8103b17db6f1a616856151124e0513bcf71440bed403f503', 
       encryptedMessage
    );
 
```
The keys are generated with EthCrypto.createIdentity().

Am I missing something or this is a bug?

**Comment by pubkey** [comment]
Looks like a bug,
Can you edit https://github.com/pubkey/eth-crypto/blob/master/test/bug-template.test.js and make a PR to reproduce this?

**Comment by pubkey** [comment]
Maybe this depends on where you use eth-crypto.
The Buffer-object will be polyfilled by webpack, browserify and others. Which build-stack do you use?

**Comment by pubkey** [comment]
Ok, so please edit the bug-template to reproduce this and make a Pull-Request. This might be a bug, but I do not think I can reproduce this myself.
