### ISSUE TITLE
Public key compression format

### ISSUE THREAD

**Issue by nugaon** [pubkey/eth-crypto#158]
## Case

Documentation
Question
## Issue

I would like to store a public key in a contract bytes32 field. With a public key compression it could be solvable.
The description of the project at the [publicKey.compress()](https://github.com/pubkey/eth-crypto#publickeycompress) section says the compression can shrink the public key length to 66 characters, where the first 2 characters are "02" or "03", but it doesn't explain depends on what. Is it parity check or something like I can recalculate from the last 64 characters?

**Comment by pubkey** [comment]
Check the secp256k1 algorithm. 02 and 03 depends on where the points are on the curve
