### ISSUE TITLE
Incorrect import for BigNumber in types

### ISSUE THREAD

**Issue by kdelwat** [pubkey/eth-crypto#16]
## Case
Bug

## Issue
The `index.d.ts` typings import BigNumber from `bn.js` as:

```js
import { BigNumber } from 'bn.js';
```
However, the `bn.js` types do not support ES6 module syntax, so the Typescript compiler throws an error:

```bash
TS2305: Module '"/mnt/c/Users/.../node_modules/@types/bn.js/index"' has no exported member 'BigNumber'.
```

Instead, the import should be:

```js
import BigNumber = require('bn.js');
```

As per https://stackoverflow.com/a/39415662.

## Info
  - Environment: node v9.11.1
  - Stack: Typescript 3.0.1

If the suggested change sounds good I'll happily put in a PR 😄

**Comment by pubkey** [comment]
Hi @kdelwat 
I [added some tests](https://github.com/pubkey/eth-crypto/commit/ba09d5a1e43933646d51a18bb3c4fe52fbbedf58) for the typings but could not reproduce the problem. Can you help me out?

**Comment by kdelwat** [comment]
@pubkey For sure, will try to get it reproduced over the weekend

**Comment by kdelwat** [comment]
@pubkey I was able to reproduce and find the source.

Minimal repo is https://github.com/kdelwat/eth-crypto-bug-reproduction, running `tsc` will show the error.

The issue only occurs if the `@types/bn.js` typings are installed. Not sure where to go from here, since it could equally be a problem with the BN typings and have nothing to do with eth-crypto. Let me know what you think 😄

**Comment by pubkey** [comment]
Thanks, that helped. Your proposed fix works and I think we should change that. I do not think this is a problem of bn.js, because it [directly exports the constructor](https://www.npmjs.com/package/bn.js#usage) which is not wrong per se.
Do you want to create a PR?

**Comment by pubkey** [comment]
I added your proposed change. Release will come as soon as the CI is ready.
