### ISSUE TITLE
async issue in master 

### ISSUE THREAD

**Issue by sivanagarajumolabanti** [pubkey/eth-crypto#175]
here below having problem in master code we do not have async keyword in encryption with public key method because in the function they used await keyword
 this issue is resolved in state-channel branch can you please merge the branch into master or put the async keyword in the encryptwithpublickey file and decryptwithprivatekey file

encryptWithPublicKey()
Encrypts the message with the publicKey so that only the corresponding privateKey can decrypt it. Returns (async) the encrypted data as object with hex-strings.

    const encrypted = await EthCrypto.encryptWithPublicKey(
        'bf1cc3154424dc22191941d9f4f50b063a2b663a2337e5548abea633c1d06ece...', // publicKey
        'foobar' // message
    );
    /* >  {
            iv: '02aeac54cb45283b427bd1a5028552c1',
            ephemPublicKey: '044acf39ed83c304f19f41ea66615d7a6c0068d5fc48ee181f2fb1091...',
            ciphertext: '5fbbcc1a44ee19f7499dbc39cfc4ce96',
            mac: '96490b293763f49a371d3a2040a2d2cb57f246ee88958009fe3c7ef2a38264a1'
        } */

**Comment by pubkey** [comment]
You do not need async if you do not use await.

**Comment by sivanagarajumolabanti** [comment]
> You do not need async if you do not use await.

yes but i am getting error while running encrypt with public key function

**Comment by sivanagarajumolabanti** [comment]
> You do not need async if you do not use await.

const encrypted =  EthCrypto.encryptWithPublicKey(
    'c0bb46de9f452892c4e04447e09d27afde2a1fb664e2b0e3c82d28901c09788fe1dc64ce98a4e2e07945b857186743f294b87a555ea1995b8e16144894b82bee', // publicKey
    'foobar' // message
);

output:
=====
Promise { <pending> }
this is what i am getting because in the encryptwith public key thereis no async keyword if i remove the await keyword above output is coming

**Comment by pubkey** [comment]
You have to await the promise in your own code
```js
const encrypted = await EthCrypto.encryptWithPublicKey(...
```
