### ISSUE TITLE
MIN_ENTROPY_SIZE in bites instead of bytes

### ISSUE THREAD

**Issue by pedrouid** [pubkey/eth-crypto#19]
I'm trying to use this package with `bip39` package to have a mnemonic for the entropy of the created identity but I keep getting the minimum entropy size error from this line:

https://github.com/pubkey/eth-crypto/blob/master/src/create-identity.js#L25

But after looking at it, isn't the MIN_ENTROPY_SIZE supposed to be in bytes? Or perhaps the check should be multiplied by 8?

**Comment by pubkey** [comment]
I wanted to implement exactly the same security like [eth-lib](https://github.com/MaiaVictor/eth-lib/blob/master/lib/account.js#L8) with uses 4*32=128 bytes of entropy.
Providing your own entropy is risky so I decided that it would be better to force the programmer to have the same entropy-size as the one which is automatically used.

Does `bip39` specify an entropy size? As far as I found out, [it doesnt](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki#generating-the-mnemonic).

**Comment by pedrouid** [comment]
I was using this library `bip39`: https://www.npmjs.com/package/bip39

```javascript
const bip39 = require('bip39')

const mnemonic = bip39.generateMnemonic()
// 'seed sock milk update focus rotate barely fade car face mechanic mercy'

const entropy = bip39.menmonicToEntropy(menmonic)
// c2f9c2327745a37844a28e224a3228c5

const byteLength = Buffer.byteLength(entropy, 'utf8')
// 32
```

Basically I just wanted to use this mnemonic for recovery while still using the `eth-crypto` library to generate an identity to keep it lightweight. We could instead integrate the generateMnemonic into `eth-crypto`?

**Comment by pubkey** [comment]
According to [this](https://github.com/bitcoinjs/bip39/blob/bafbcd352a6a5275bbc640a79c3917d0baee5bc8/index.js#L116) the default strength of this module is also 128bytes. 
As you can see on the [online-tool](https://iancoleman.io/bip39/), the size of `BIP39 Seed` is always 128bytes. I have no full understanding of the bip39-protocol, but shouldn't the seed be used to generate the private key?

**Comment by pedrouid** [comment]
Yeah, you're right! My bad! That was my fault
