### ISSUE TITLE
Eth encrypt & decrypt fails in some browsers.

### ISSUE THREAD

**Issue by ibudisteanu** [pubkey/eth-crypto#205]
Hello

I have some issues with this package. I use it to encrypt & decrypt data.

With the same private keys, public keys, on some browsers it works to encrypt/decrypt, while on other browser/versions it fails. I am following the example closely, but it simply fails on some browser versions.

![image](https://user-images.githubusercontent.com/17750489/73910613-b0e5c880-4864-11ea-8767-6d68977b38c2.png)

One such browser is this one, that I couldn't ever get it encrypt/decrypt 

Chrome Version 76.0.3809.87 (Official Build) (64-bit) under Ubuntu 18

LE: Sometimes, decrypt returns an empty Buffer(UInt8Array) with length 0 while with some other browsers on the same decrypt data I get my encrypted data decrypted.

**Comment by ibudisteanu** [comment]
to show you an example the following code fails on Chrome Version 76.0.3809.87 (Official Build) (64-bit) under Ubuntu 18
but works on Version 65.0.3325.181 (Official Build) (64-bit) Ubuntu 16

```
  async testEncryptDecrypt( text = StringHelper.generateRandomId(100) ){

        const bob = EthCrypto.createIdentity();

        const encrypted = await EthCrypto.encryptWithPublicKey(
            bob.publicKey, // by encryping with bobs publicKey, only bob can decrypt the payload with his privateKey
            text // we have to stringify the payload before we can encrypt it
        );
        const encryptedString = EthCrypto.cipher.stringify(encrypted);

        const encryptedObject = EthCrypto.cipher.parse(encryptedString);

        const decrypted = await EthCrypto.decryptWithPrivateKey(
            bob.privateKey,
            encryptedObject
        );

        console.log("testEncryptDecrypt", decrypted, text );

        return decrypted === text;

    }
```

**Comment by ibudisteanu** [comment]
Even a simplified version fails.

```
async testEncryptDecrypt( text = StringHelper.generateRandomId(100) ){

        const bob = EthCrypto.createIdentity();

        const encrypted = await EthCrypto.encryptWithPublicKey(
            bob.publicKey, 
            text 
        );
        const decrypted = await EthCrypto.decryptWithPrivateKey(
            bob.privateKey,
            encrypted
        );

        console.log("testEncryptDecrypt", decrypted, text );

        return decrypted === text;

    }
```

Decription fails with the above error

**Comment by ibudisteanu** [comment]
Even stranger, the above code works only if I access **127.0.0.1**, but fails with domain, 0.0.0.0, local ip, ipv4. I use Vue2 and webpack dev server.

**Comment by ibudisteanu** [comment]
I have identified something interesting. I have runned this code 

```
    async testEncryptDecrypt( text = "38123789127398127983712983712983721987321897ABCD871893721389217" ){

        const encrypted = await EthCrypto.encryptWithPublicKey(
            "030dddc2e1cb1f9c5c3463399f0b539e2f2a9d42678f596cef95ce301087c05836",
            text
        );
        const encryptedString = EthCrypto.cipher.stringify(encrypted);

        console.log("encryptedString", encryptedString);

        const encryptedObject = EthCrypto.cipher.parse(encryptedString);

        const decrypted = await EthCrypto.decryptWithPrivateKey(
            "6b463fdd6b15df6da6753fe8d1a5973b133c7a4aed77b38b145b11987cf27876",
            encryptedObject
        );

        console.log("testEncryptDecrypt", decrypted, text );

        return decrypted === text;

    }
```

Accessing on Chrome on 127.0.0.1, I get the following message:


encryptedString 6a3f8faad9fe1cc4fee231fdaa5e35a40367a044f82613de9994d8fb7d40abe47467d582ae44168ec9f8e66a5d6b802fd034466ddd04f37396b89ffe9c9ea8bfac650fffdfb197cff237227d93c0c68fb398fe905074e3c252639a29287ebdc6f03cc6a7cb50f1e20648bd55672a66e33c577b99242697fc53f38f63dbad2d4dbf1426bf2644b7c5ddf473ead303364479


When I access it on ipv4, localip, even 0.0.0.0  the result is smaller and after it throw the above mentioned error.


encryptedString 1a597e54950ce9253d742c767b7c3745023c80ed10b44cce2cb90c7e575fd76540f96f8c6caca35e59c86a8a9ac8b6560260a696d70f9d53a3bf0d143cda62a27bac2139450cfd2f78b19d79635fd67910daed907622174aa9ead7a5f1aec2aeae

Definitely data is missing, but why is it missing?

**Comment by pubkey** [comment]
Please clone the repo and run `npm run test:browser`.
Does this work?
If not, add your described code to the test-suite and make a PR. I will try to help then.

**Comment by ibudisteanu** [comment]
Your tests passed. It opened firefox, not chrome so I couldn't check for chrome.

The issue, I have with your package is that it doesn't work when I access the bundle (I even had es6 bundle) with pure html when it is serverd from non-127.0.0.1 address. On 0.0.0.0, local ip, ipv4 address or domain encryption fails.

I ended up using this package `eth-ecies` which works very well. https://github.com/libertylocked/eth-ecies#readme
