### ISSUE TITLE
typescript module warnings

### ISSUE THREAD

**Issue by acarnagey** [pubkey/eth-crypto#234]
## Case
bug

## Issue
when running the typescript react app locally, the console gets filled with warnings

## Info 
  - Environment: Browser - Chrome Version 80.0.3987.163 (Official Build) (64-bit) , Mac 10.15.4
  - Stack: Typescript,  React

## Code

```ts
import EthCrypto, {Encrypted} from 'eth-crypto';
```

browser console output
```
react_devtools_backend.js:6 ./node_modules/ethereumjs-common/dist/chains/index.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find source file '../../src/chains/index.ts': Error: Can't resolve '../../src/chains/index.ts' in '/Users/adam/git/coa/mypass-frontend/node_modules/ethereumjs-common/dist/chains'
r @ react_devtools_backend.js:6
warnings @ client:135
(anonymous) @ socket.js:47
sock.onmessage @ SockJSClient.js:63
EventTarget.dispatchEvent @ eventtarget.js:51
(anonymous) @ main.js:279
SockJS._transportMessage @ main.js:277
EventEmitter.emit @ emitter.js:50
WebSocketTransport.ws.onmessage @ websocket.js:35
11:52:59.716 react_devtools_backend.js:6 ./node_modules/ethereumjs-common/dist/hardforks/index.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find source file '../../src/hardforks/index.ts': Error: Can't resolve '../../src/hardforks/index.ts' in '/Users/adam/git/coa/mypass-frontend/node_modules/ethereumjs-common/dist/hardforks'
r @ react_devtools_backend.js:6
warnings @ client:135
(anonymous) @ socket.js:47
sock.onmessage @ SockJSClient.js:63
EventTarget.dispatchEvent @ eventtarget.js:51
(anonymous) @ main.js:279
SockJS._transportMessage @ main.js:277
EventEmitter.emit @ emitter.js:50
WebSocketTransport.ws.onmessage @ websocket.js:35
11:52:59.717 react_devtools_backend.js:6 ./node_modules/ethereumjs-util/dist/account.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find source file '../src/account.ts': Error: Can't resolve '../src/account.ts' in '/Users/adam/git/coa/mypass-frontend/node_modules/ethereumjs-util/dist'
```...

**Comment by pubkey** [comment]
Do these files exist in your node_modules folder?
For me it looks like the problem must be fixed in `ethereumjs-common` and `ethereumjs-util` not here.

**Comment by acarnagey** [comment]
Thanks for the quick response.  I ended up excluding ethereumjs-common/tx/util and rlp from the webpack source-map-loaders ```{
        enforce: 'pre',
        test: /\.js$/,
        loader: 'source-map-loader',
        exclude: [
          (path.resolve(__dirname, 'node_modules') + '/ethereumjs-common'),
          (path.resolve(__dirname, 'node_modules') + '/ethereumjs-util'),
          (path.resolve(__dirname, 'node_modules') + '/ethereumjs-tx'),
          (path.resolve(__dirname, 'node_modules') + '/rlp')
        ]
      },```
Yeah those files aren't there in my node_modules folder.  It seems that ethereumjs-tx and ethereumjs-common projects have been archived and have been moved to ethereumjs-vm so I don't think I will get any fix for those source files.  Any plans to use ethereumjs-vm?

**Comment by pubkey** [comment]
I didnt know they where archived. I have no plans to migrate but will happily accept a pull request.

**Comment by pubkey** [comment]
Closing this. Please make a PR
