### ISSUE TITLE
react-native support

### ISSUE THREAD

**Issue by pedrouid** [pubkey/eth-crypto#25]
I really want to use this library for a react-native library but I'm getting an error from `eth-lib` dependency because of the crypto library.

The react-native app that I'm testing has `react-native-crypto` polyfilled using `rn-nodeify` but this library still fails to get the crypto library from window.

Has anyone managed to run `eth-crypto` on a react-native environment??

**Comment by pubkey** [comment]
Hi @pedrouid 
So we use this parts of `eth-lib`:

```ts
// in sign.js
import {
    decodeSignature, // uses eth-lib/bytes
    encodeSignature  // uses eth-lib/bytes
} from 'eth-lib/lib/account';

// in create-identity.js
import {
    fromPrivate // uses secp256k1
} from 'eth-lib/lib/account';

import { keccak256 } from 'eth-lib/lib/hash'; // has no dependency

import Bytes from 'eth-lib/lib/bytes';
```

So I think the problem comes from [this line](https://github.com/MaiaVictor/eth-lib/blob/master/lib/bytes.js#L7) which is used in the random-function of `eth-lib`.

Since `eth-crypto` do not use eth-libs random-function, we could refactor out this dependency.
A PR is welcomed.

**Comment by pubkey** [comment]
Do you know how a safe random byte-array can be created with react-native?
Maybe there is a npm-module that is battle-proofed and works with browsers, nodejs and react-native.

**Comment by pedrouid** [comment]
Cryptography with react-native is a hot mess to be honest. The best solution so far is to use [tradle/rn-nodeify](https://github.com/tradle/rn-nodeify) polyfills. You can see the dependencies it installs. For random byte generation it uses [react-native-randombytes](https://github.com/mvayngrib/react-native-randombytes#readme)

**Comment by pubkey** [comment]
Can you try creating a bytearray with react native and pass it into createIdendity()?
Then you would not run into the require statement of crypto

**Comment by pubkey** [comment]
Closing. I think this can be fixed with the proposed workaround. Please reopen if it does not.

**Comment by recepaltas** [comment]
I have an error on react native app more than 16 character decrypt. I dont know how can i fix this. Please help me. A sample code may be you can show me. 
Thanks a lot

**Comment by pedrouid** [comment]
btw I created an isomorphic version of eccrypto which would help with react-native support

https://www.npmjs.com/package/eccrypto-js

It's backwards compatible with eccrypto so you should be able to just replace it with the same API

**Comment by alvesluc** [comment]
@pedrouid Can you make a step-by-step on how to do the workaround? I'm trying for a few hours and didn't manage to make it work in.
