### ISSUE TITLE
Provide an ES modules build

### ISSUE THREAD

**Issue by lastmjs** [pubkey/eth-crypto#274]
It would be great to have an ES modules build for this library, so that it can be run in the browser directly with minimal build tools. Leaving bare specifiers on imports would be just fine. For example, right now the library will not run in the browser with my build tool, Zwitterion, which relies on native ES modules, and just rewrites bare specifiers.

**Comment by pubkey** [comment]
Can you make a PR with what you think muse be changed?
As far as I know, having a [module index](https://github.com/pubkey/eth-crypto/blob/master/package.json#L21) counts as es build :)
