### ISSUE TITLE
Browser decryption failed with "Bad MAC"

### ISSUE THREAD

**Issue by pranavburnwal** [pubkey/eth-crypto#281]
The decryption failed with the "Bad MAC" error on the browser.
This case happens only like ~ 1/300 cases. Rest 299 decrypt with perfectly fine.

Even the cases that fail are being able to decrypt on Node easily without any problems. Points me to check the newer builds.
We are using Webpack and have been using this same module the same version for more than a year. and this started recently. I am trying to trace right now but any help would be appreciated.
The problem might have been in "eccrypto" module as well as the error comes from that module. 

Thank you for your time.

Edit: add more details.

**Comment by pubkey** [comment]
Please reopen while using the issue template and paste some code to reproduce. There is no way that someone can help you with that little information.

**Comment by s00179906** [comment]
Anything on this? I am getting the same error. I am encryping data with my public key and signing with private. Then when i try to decrypt the i get the following error: browser.js?4273:16 Uncaught (in promise) Error: Bad MAC
    at assert (browser.js?4273:16)
    at eval (browser.js?4273:258)
assert @ browser.js?4273:16
eval @ browser.js?4273:258
Promise.catch (async)
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js?5c40:165
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js?5c40:173
invoker @ runtime-dom.esm-bundler.js?830f:301

**Comment by pubkey** [comment]
@s00179906 can you make a PR with a failing test case?

**Comment by s00179906** [comment]
sorry i dont know how to do that but i can provide the detailed code with it failing. I really need to get it to work badly as im using this for a college assignment which is due in weeks time.

**Comment by pubkey** [comment]
If you just want a quick fix, you likely should try downgrading the nodejs version.
I cannot start fixing bugs without a reproducible test. Too many people have submitted issues in the past where I wasted hours just to find out what they did wrong.

**Comment by s00179906** [comment]
well im using the library on my frontend client. VueJS. i mean it works perfectly when i use other peoples public keys to encrypt. But when i want to encrypt data myself and decrypt it i get a BAD MAC error?

**Comment by s00179906** [comment]
ok so i just downgraded from 1.9.0 to 1.8.0 and im still getting the bad mac error. Could it be my code? What version should i downgrade to?

**Comment by pubkey** [comment]
Sorry, downgrading will not help when you use this lib in the frontend, I thought you use it in nodejs.

**Comment by s00179906** [comment]
ok if i move it to my api in nodejs will it fix the issue?

**Comment by s00179906** [comment]
ok so i just tried this via nodejs and its working thanks for your help seriiously!

**Comment by s00179906** [comment]
ok im back lol, so i tried encrypting/decrypting with my own keys with my api using postman and it works perfectly but when i try to decrypt the encrypted messages created through code (my mobile app) i still get a Bad Mac. most likely theres something wrong in my code. All im doing is taking  strings from an object, iterating over it and for each string i encrypt it. not sure what im doing wrong
