### ISSUE TITLE
Error in recover

### ISSUE THREAD

**Issue by adamskrodzki** [pubkey/eth-crypto#3]
In file:
https://github.com/pubkey/eth-crypto/blob/master/src/recover-public-key.js

line 

    let sigOnly = signature.substring(0, signature.length - 1);

should be -2 
that is hex value by removing single sign You get invalid Hex

Example to test 
{ payload: { data: 'something', val: 5, other: 'something else' },
  signature: '0x0c11421ca7bd14294c7b2fc5ba5f12f482c59bd5c7b11fc9f7ae75234e93b23b758826cf31a877bf704a1a7d26e7ffc059c357ba43dc9c30f1682c79bff9dab71c',
  signer: '55196b97415c12d0056a81506632a3336e66571fcebbe20a0cad7776cd1a5c8ef44d18b23930a5b23fd06a30b2fdff18a0810a9ecfaf31c6e874a938b41fd6cd' }

var payload = signedMsg.payload;
		
		var resolvedAddress = ethcrypto.recover(
		      signedMsg.signature,
		      ethcrypto.hash.keccak256(JSON.stringify(payload)) // signed message hash
		  );
		var address = ethcrypto.addressByPublicKey(signedMsg.signer);

**Comment by pubkey** [comment]
I added a test but could not reproduce your problem. Please make a PR with a failing test.

**Comment by lacabra** [comment]
I get the same error as @adamskrodzki reported. If I try to do a round trip with sign and recover, I get the error on recover. Using the same example as in the documentation:
```
const message = 'foobar';
const messageHash = EthCrypto.hash.keccak256(message);
const signature = EthCrypto.sign(
      '0x107be946709e41b7895eea9f2dacf998a0a9124acbb786f0fd1a826101581a07', // privateKey
      messageHash // hash of message
);
const signer = EthCrypto.recover(
      signature,
      messageHash 
);
```
throws the following error:
```
index.js:799 Uncaught TypeError: Invalid hex string
    at hexWrite (index.js:799)
    at Uint8Array.write (index.js:873)
    at fromString (index.js:233)
    at from (index.js:134)
    at new Buffer (index.js:113)
    at recoverPublicKey (recover-public-key.js:20)
    at Object.recover (recover.js:11)
    at Object../main.js (main.js:36)
    at __webpack_require__ (bootstrap:19)
    at Object.0 (immutable.js:19)
```
I don't understand how the test #3 can pass, and we get this error, though; but I agree that the line that @adamskrodzki  highlights above cannot be right: if `signature` has an even number of digits, and you cut its length by 1, then you end up with an odd number of digits that throws the above error.

**Comment by pubkey** [comment]
@lacabra I added your code as test, but could not reproduce. Please adjust the test until it fails.

**Comment by adamskrodzki** [comment]
I guess it might be something with different way this script is executed in test and by us. 

@lacabra how do You run your code?

**Comment by adamskrodzki** [comment]
@pubkey 

please run tests with both values 

let sigOnly = signature.substring(0, signature.length - 1);

let sigOnly = signature.substring(0, signature.length - 2);

You will see that both values tests pass, so probably coverege of this tests is not full

**Comment by adamskrodzki** [comment]
@pubkey 
@lacabra 

I've found work around 

library works just fine with 
node v8.11.1
and breaks with
node v6.12.3

**Comment by pubkey** [comment]
@adamskrodzki 
You are right. The removement of the last char happened because web3 adds the `v`-value (26/27) to the end of the signature. We have to remove it and somehow it worked even if the hex-buffer had an additional char. Fix will come soon.
