### ISSUE TITLE
Which cryptographic algorithm is used for encryption and decryption.

### ISSUE THREAD

**Issue by ahamed** [pubkey/eth-crypto#327]
Hello @pubkey ,
I am using solidity for research purposes. So I've decided to use this library to encrypt some of my data. As it is for research purpose so I have to mention that which encryption algorithm do you use for `encryptWithPublicKey()` and `decryptWithPrivateKey()` methods.

I have another problem. If I encrypt my data with `encryptWithPublicKey()` method then can I decrypt the data by **Solidity** language?

I am completely new in this sector. Any help would be appreciatable.

**Comment by pubkey** [comment]
Please use the issues for bugs or features.
Check the code to find the encryption method.

You cannot decrypt data in solidity with this library. Also it is very unlikely that you ever should do that since every piece of data in a smart contract is public anyway, also your decryption key.
