### ISSUE TITLE
documentation : can I sign off-chain and verify on-chain just with ethers ?

### ISSUE THREAD

**Issue by SvenMeyer** [pubkey/eth-crypto#391]
Sorry to post that as an issue ...

Actually, I want to sign a message off-line, off-chain, using Javascript only, and then verify within a smart contract that the message has been signed by the right address. 
Looks like that `eth-crypto` is exactly doing this, there is even a tutorial !

I am just wondering if I can't do that with just ethers, and if not, what is missing that I need `eth-crypto` ?

**Comment by pubkey** [comment]
When I created eth-crypto, there was no other lib that made this possible.
Maybe in the meantime there are many libs that do exactly the same.
