### ISSUE TITLE
Get public key from address

### ISSUE THREAD

**Issue by dufferzafar** [pubkey/eth-crypto#4]
I couldn't find a function to get an account's public key from its address.

I need to encrypt some data with the public key of a user's account.

I'm new to ethereum programming, so pardon me if this is the wrong place to raise such request.

**Comment by pubkey** [comment]
Its not possible to do this because the address is a hash of the publicKey.
You could find a signed transaction of this address on the chain an than derive the public key from the signature.

**Comment by dufferzafar** [comment]
Hey, I'm doing this on a private network (ganache) and need to write a test that encrypts some data with the public key of the user & decrypts it using the private key.

But the problem is that there might be no signed transaction from that account.

**Comment by huss3in** [comment]
i think you must send this public key between the two parties (encryptor & decrypter )
