### ISSUE TITLE
using outdated package ethereumjs-tx

### ISSUE THREAD

**Issue by TimDaub** [pubkey/eth-crypto#425]
https://github.com/pubkey/eth-crypto/blob/2d650e89e533b72b352a7da1e80836f2fbbcb64d/package.json#L115

is using a deprecated package: https://www.npmjs.com/package/ethereumjs-tx

```
New package name format for new versions: @ethereumjs/tx. Please update.
```

**Comment by pubkey** [comment]
Please make a PR to update the version. There might be some other changes to be done to keep the tests running.

**Comment by TimDaub** [comment]
I can send a PR later. Did u close by accident?

**Comment by pubkey** [comment]
Yes you can send a PR later.

**Comment by pubkey** [comment]
@TimDaub  any update on this?

**Comment by TimDaub** [comment]
Hey @pubkey not yet. But it's because I've been busy. Solving this issue continues to be on my list. If, however, you feel like solving it before, I'm happy to give assignment away.
