### ISSUE TITLE
signTransaction is defaulting mainnet chain-id "1" without giving option to change

### ISSUE THREAD

**Issue by TimDaub** [pubkey/eth-crypto#426]
https://github.com/pubkey/eth-crypto/blob/2d650e89e533b72b352a7da1e80836f2fbbcb64d/src/sign-transaction.js#L20

`new Transaction()` contructor without option argument defaults to "mainnet and petersburg" as chain id and hard fork [1].
But I'm e.g. not using "mainnet and petersburg" in my development environment, hence for every transaction that I sign with `eth-crypto` mainnet is assumed and my transaction fails in `geth` with an "invalid sender" error.

Solution:

Allow users to specify chainId and hardfork somewhere so that it can get passed along to ethereumjs-tx.

Dependency:

This issue may be dependent on #425 

## References

- 1: https://www.npmjs.com/package/ethereumjs-tx#chain-and-hardfork-support

**Comment by pubkey** [comment]
Closing this as it seems noone wants to work on it. PR still welcomed.
