### ISSUE TITLE
Question regarding a strange addition in `sign.js`

### ISSUE THREAD

**Issue by DIYgod** [pubkey/eth-crypto#433]
Code: https://github.com/pubkey/eth-crypto/blob/master/src/sign.js#L26

We found that the signature results were different from [go-ethereum](https://github.com/ethereum/go-ethereum), so we looked at the code and found that a `1c` or `1b` was added to the end of the signature. We are confused about this, can you tell me what is the purpose of this addition?

Thank you very much!

**Comment by pubkey** [comment]
To be honest, I have no idea this was so long ago. I fiddles stuff together until it worked with the ethereum javascript clients.
Maybe this helps https://ethereum.stackexchange.com/questions/42455/during-ecdsa-signing-how-do-i-generate-the-recovery-id
