### ISSUE TITLE
Invalid key length

### ISSUE THREAD

**Issue by dufferzafar** [pubkey/eth-crypto#5]
I'm using the private key of an account from Ganache:

![image](https://user-images.githubusercontent.com/1449512/38821026-10f5ec6a-41bd-11e8-8e6f-8289b1e347ea.png)

But when converting it to a public key, I get invalid key length error.

```js
> EthCrypto = require("eth-crypto");
> pvt_key = "43137cdb869f4375abfce46910aa24d528b2152c5a396158550158fbdb160b4f"
> EthCrypto.publicKeyByPrivateKey(pvt_key);

RangeError: private key length is invalid
```

**Comment by dufferzafar** [comment]
Well, this was embarassing. You just need to prefix the key with `0x`

```js
> ethUtils.privateToAddress("0x92ee9bb497c7ad27025b6813587b901d881d85369e2b9d8abbf52e36b8f3244b");
```

**Comment by pubkey** [comment]
Hey @dufferzafar 
I know it's a huge pain that each lib in the ethereum-ecosystem requires different formats of cryptograpic keys.

I now added some code to auto-add the `0x` if it's missing.

**Comment by dufferzafar** [comment]
Now, I'm actually using your [`ethereum-encryption`](https://www.npmjs.com/package/ethereum-encryption) which I believe is an older version of this lib.

It doesn't need `0x` prefixes and best of all, returns an encrypted string, rather than an object containing ciphertext, iv etc.

I feel beginners will find that easy to use. I know I do.

**Comment by pubkey** [comment]
yes, `ethereum-encryption` is an old version of this lib.
The encrytion-method of the old module is slower and less secure because it does not use an ephemeral publicKey. Also it's code has a big overhead because it's copied from bitcore-lib.

**Comment by dufferzafar** [comment]
Okay, so suppose I wanted an encrypted string (instead of the object) - how would I do that?

I need to pass the encrypted string onto a contract function.

**Comment by pubkey** [comment]
Hi @dufferzafar 
That is a good use-case. JSON.stringify would work but also add some overhead.
I added two functions to stringify and parse the encryption-object.
It also compresses the publicKey into the 'smaller' one.

[stringify](https://github.com/pubkey/eth-crypto#cipherstringify)
[parse](https://github.com/pubkey/eth-crypto#cipherparse)
