### ISSUE TITLE
Use `encryptWithPublicKey()` with public key from `eth_getEncryptionPublicKey`

### ISSUE THREAD

**Issue by bluet** [pubkey/eth-crypto#576]
First, thanks for the awesome module. I'm having fun with it, but stuck in the following problem for weeks.  
I tried StackExchange, reddit, and gitter, but still cannot find an answer.

### What's expected
```
EthCrypto.encryptWithPublicKey(
    ethereum.request("eth_getEncryptionPublicKey", account)
);
```
Or,
```
EthCrypto.encryptWithPublicKey(
    someConversions(
        ethereum.request("eth_getEncryptionPublicKey", account)
    )
);
```

### What really happened

1. The public key seems different from eth-crypto's `recoverPublicKey()` and `ethereum.request("eth_getEncryptionPublicKey", account)`.
2. When using them to, for example, encrypt messages:
    - Works:
        - Use _EthCrypto_ with _EthCrypto recovered public key_.
        - Use _Ethereum (MetaMask)_ with _EthCrypto recovered public key_. (with some conversions)
        - Use _Ethereum_ with _Ethereum public key_.
    - Doesn't work:
        - Use _EthCrypto_ with _Ethereum (MetaMask) public key_. **(But this is what I need)**
    
|  | EthCrypto recovered public key | Ethereum (MetaMask) public key |
|-|-|-|
| `EthCrypto.encryptWithPublicKey()` | ✅ | ❌ |
| `sigUtil.encrypt()` | ✅ (conversion needed) | ✅ |

### Question
1. **How to make the pubkey from `ethereum.request("eth_getEncryptionPublicKey")` and `EthCrypto.encryptWithPublicKey()` work together?**
2. Are they (those pubkeys) totally different things?
3. Is there any way to convert from one to another?

### Additional info
- The gist of my test codes and outputs: https://gist.github.com/bluet/e944003d6d2069666799cb398d48bb01
- Detailed description in post on StackExchange: https://ethereum.stackexchange.com/questions/123548/got-different-public-keys-from-same-private-key-using-eth-crypto-recoverpublick
- Discussion on Reddit: https://www.reddit.com/r/ethdev/comments/tbco3r/got_different_public_keys_from_the_same_private/

**Comment by bluet** [comment]
Sorry, I'm not sure if this is a bug or feature request, so I didn't create PR.

The gist contains codes I used in testing (see result matrix in OP). If @pubkey or anyone found anything needed is missing, please let me know. Thanks!

Appreciate if anyone can help.

**Comment by bluet** [comment]
Sorry, I'm not sure if this is a bug or feature request, so I didn't create PR.

The gist contains codes I used in testing (see result matrix in OP). If @pubkey or anyone found anything needed is missing, please let me know. Thanks!

Appreciate if anyone can help.

**Comment by pubkey** [comment]
The issue section is no support hotline.
Make a PR if you want to change anything.
Do never @ me just because you are too lazy to research by your own.
