### ISSUE TITLE
Error while decrypting the object data.

### ISSUE THREAD

**Issue by HP213** [pubkey/eth-crypto#67]
I am using same code as given here

https://github.com/pubkey/eth-crypto/blob/master/tutorials/encrypted-message.md

But it is showing error and not decrypting the encrypted data.
It is working on string but not on object data.

### Code :

const EthCrypto = require('eth-crypto');
const alice = EthCrypto.createIdentity();
const bob = EthCrypto.createIdentity();
const secretMessage = 'My name is Satoshi Buterin';

async function call(){
  const signature = EthCrypto.sign(
    alice.privateKey,
    EthCrypto.hash.keccak256(secretMessage)
  );
  console.log(signature);

  const payload = {
    message: secretMessage,
    signature
  };
  console.log("payload :", payload);

  const encrypted = await EthCrypto.encryptWithPublicKey(
    bob.publicKey, // by encryping with bobs publicKey, only bob can decrypt the payload with his privateKey
    JSON.stringify(payload) // we have to stringify the payload before we can encrypt it
);

  console.log("encrypted :", encrypted);

  const encryptedString = EthCrypto.cipher.stringify(encrypted);
  console.log("encryptedString : ", encryptedString);

  const encryptedObject = EthCrypto.cipher.parse(encryptedString);
  console.log("encryptedObject :", encryptedObject);

  const decrypted = await EthCrypto.decryptWithPrivateKey(
    bob.privateKey,
    encryptedObject
  );
  console.log(JSON.parse(decrypted));
}

call();

### **Output**:

![ss](https://user-images.githubusercontent.com/34127674/60806282-38b90680-a1a0-11e9-8f81-fbe462683379.PNG)

**Comment by pubkey** [comment]
Which node version do you have?
Maybe this is equal to https://github.com/pubkey/eth-crypto/issues/47

**Comment by HP213** [comment]
node version : 10.16.0
npm version : 6.9.0

**Comment by HP213** [comment]
Which encryption algorithm are you using here btw?

**Comment by pubkey** [comment]
[eccrypto](https://www.npmjs.com/package/eccrypto) is used for the encryption.

**Comment by pubkey** [comment]
Closing this. Same problem as https://github.com/pubkey/eth-crypto/issues/47
