### ISSUE TITLE
Error Finding module while running

### ISSUE THREAD

**Issue by HP213** [pubkey/eth-crypto#76]
I have an error while running Eth-crypto, although it is not creating any problem.  What's the reason behind it?
![ecdh](https://user-images.githubusercontent.com/34127674/61171778-e578f680-a599-11e9-9d5f-ce2e4c5827e1.PNG)

**Comment by pubkey** [comment]
Closed. Same problem as https://github.com/pubkey/eth-crypto/issues/47
